### PR TITLE
Add Pass-thru Feature

### PR DESCRIPTION
**Pull request by yzanhua**
Add pass-thru feature:
Now it supports opening a regular HDF5 file using LOG-VOL.
It first checks if a file is regular or log-based during the file opening. Then for other operations, it calls the native vol if it is a regular file and calls LOG-VOL if it is log-based.

Three test cases are added to test the pass-thru features. But currently, they do not support parallel-test.

### CODE REVIEW

**Comment by wkliao** [comment]
github actions failed. Check the logs there.

**Comment by wkliao** [comment]
Remove your names in the source code comments.
Github history can show all contributions.

**Comment by wkliao** [comment]
We do not copy a test program directly from HDF5 repo.
See examples in [tests/nc4](https://github.com/DataLib-ECP/vol-log-based/tree/master/tests/nc4/)
for how to download and test at the make time.

**Comment by wkliao** [comment]
@khou2020 
Please check this PR and merge it if it is OK with you.

**Comment by khou2020** [comment]
> @khou2020 Please check this PR and merge it if it is OK with you.

It is outdated. It should be updated to match with the latest master.

**Comment by wkliao** [comment]
The github detects no conflict of this PR to the master branch.
See it on a web browser. It can be rebased and merged to master branch

**Comment by khou2020** [comment]
> The github detects no conflict of this PR to the master branch. See it on a web browser. It can be rebased and merged to master branch

I added some comments

**Comment by wkliao** [comment]
> > The github detects no conflict of this PR to the master branch. See it on a web browser. It can be rebased and merged to master branch
> 
> That was wrongly posted.
> 
> I added some comments in the code.

Why do you think this PR has a conflict?
I also did not see your comments in this PR.

**Pull request merged**
