### PR TITLE
Change to min. HDF5 1.13 version

### PR DESCRIPTION
**Pull request by brtnfld**
The VOL APIs are HDF5 v1.13 based, so set that as the minimum version needed.

### CODE REVIEW

**Comment by khou2020** [comment]
Are the first 3 commits merged previously?

**Comment by brtnfld** [comment]
yes, it is just the last commit

**Comment by khou2020** [comment]
Can it be rebased first?

**Comment by wkliao** [comment]
@brtnfld 
There is a conflict if rebasing this PR.
Could you please fix this?

**Pull request closed without merging**
