### PR TITLE
Integeration of Passthrough Vol

### PR DESCRIPTION
**Pull request by yzanhua**

### CODE REVIEW

**Comment by yzanhua** [comment]
This pull request tries to do the following:
1. when reading a file, first check if this is a regular HDF5 file or a log based HDF5 file.
2. If it is a regular file, direct all subsequent HDF5 requests to the underlying vol.
3. If it is a log based file, use log vol as usual.

**Comment by yzanhua** [comment]
[HDF5 Forum url](https://forum.hdfgroup.org/t/vol-unable-to-write-a-dataset-at-file-close-time/10378)
This issue of creating and writing a new dataset inside of VOL at file close.

**Comment by wkliao** [comment]
If using H5P_DEFAULT can avoid the error, then please use it in this PR.
Also, add comments in the source codes to describe this issue. Add the
reference to this PR and URL to HDF Forum,

Create a new issue, so we will be reminded when/if HDF5 decides to
fix this in a future release.

Once the above is done, we can merge this PR.

**Comment by wkliao** [comment]
Are there any test programs to test this feature?

**Comment by yzanhua** [comment]
Added tests to test Log VOL as a passthru VOL.

Currently, Mac / build fails. This is probably due to that master branch also fails.

**Comment by wkliao** [comment]
I believe the bug has been fixed in the master branch.
Please rebase this PR.

**Comment by wkliao** [comment]
Please check the log of github actions. There are error messages.

**Comment by wkliao** [comment]
The messages from the github action logs appear to be unrelated to this PR.

**Pull request merged**
